# Generated by Django 5.0.3 on 2024-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_supply_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='تصویر محصول'),
        ),
    ]
