# Generated by Django 5.0.3 on 2024-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_supply_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='color',
            field=models.ManyToManyField(related_name='goods', to='goods.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='size',
            field=models.ManyToManyField(related_name='goods', to='goods.size', verbose_name='اندازه'),
        ),
    ]
