# Generated by Django 5.0.3 on 2024-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_supply_color_alter_supply_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='color',
            field=models.ManyToManyField(default='بدون رنگ', related_name='colors', to='goods.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='size',
            field=models.ManyToManyField(default='بدون اندازه', related_name='sizes', to='goods.size', verbose_name='اندازه'),
        ),
    ]
