# Generated by Django 5.0.3 on 2024-04-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_supply_color_alter_supply_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='color',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='count',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='size',
        ),
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_color', to='goods.color', verbose_name='رنگ محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='goods.size', verbose_name='سایز محصول')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_supply', to='goods.supply', verbose_name='نام محصول')),
            ],
        ),
    ]
