# Generated by Django 5.0.3 on 2024-04-05 21:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0007_alter_supply_color_alter_supply_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2024, 4, 5, 21, 10, 1, 574567, tzinfo=datetime.timezone.utc), verbose_name='تاریخ و ساعت ثبت')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.supply', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
