# Generated by Django 5.0.3 on 2024-04-06 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 13, 27, 12, 460160, tzinfo=datetime.timezone.utc), verbose_name='زمان ثبت'),
        ),
    ]
