# Generated by Django 5.0.3 on 2024-04-06 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 21, 37, 32, 667168, tzinfo=datetime.timezone.utc), verbose_name='زمان ثبت'),
        ),
    ]
